#!/usr/bin/env bash

# cron doesn't have the session's display or DBus address
export DISPLAY=:0
export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/$(id -u)/bus"

cinnamon-screensaver-command --lock
