#!/usr/bin/env ruby

`git branch`
  .split("\n")
  .select { |branch| branch =~ /\d$/ }
  .map { |branch| branch.gsub(/\*/, '').strip }
  .map { |branch| branch.gsub(/_\d+$/, '') }
  .tally
  .sort_by(&:last)
  .each { |branch, count| puts "#{count.to_s.ljust(4)} #{branch}" }
